const BookList = [
  {
    image: "thewelthofnations.png",
    imgalt: "the wolves of nations",
    author: "Adam Smith",
    title: "The Wealth of Nations",
    commentno: 14,
    rating: 4.6,
    rateno: 164,
    canceledPrice: 15.5,
    currentPrice: 10.5,
  },
  {
    image: "mathermargarita.png",
    imgalt: "mather margarita",
    author: "Mikhail Bulgakov",
    title: "Mather Margarita",
    commentno: 14,
    rating: 4.6,
    rateno: 164,
    canceledPrice: 15.5,
    currentPrice: 10.5,
  },
  {
    image: "memoriesofnonememy.png",
    imgalt: "memories of non enemy combatant",
    author: "Mikhail Bulgakov",
    title: "From the Memories of a Non-Enemy Combatant",
    commentno: 14,
    rating: 4.6,
    rateno: 164,
    canceledPrice: 15.5,
    currentPrice: 10.5,
  },
  {
    image: "morethanthis.png",
    imgalt: "More than this",
    author: "Erik Spiekermann",
    title: "Hello I am Eirk",
    commentno: 14,
    rating: 4.6,
    rateno: 164,
    canceledPrice: 15.5,
    currentPrice: 10.5,
  },
  {
    image: "thegodfather.png",
    imgalt: "the godfather",
    author: "Mario Puzo",
    title: "The Godfather",
    commentno: 14,
    rating: 4.6,
    rateno: 164,
    canceledPrice: 15.5,
    currentPrice: 10.5,
  },
  {
    image: "thenames.png",
    imgalt: "The names",
    author: "Don Dellilo",
    title: "The Names",
    commentno: 14,
    rating: 4.6,
    rateno: 164,
    canceledPrice: 15.5,
    currentPrice: 10.5,
  },
  {
    image: "sunbeyondsun.png",
    imgalt: "sun beyond sun",
    author: "Daniel Gargallo",
    title: "Sun Beyond Sun",
    commentno: 14,
    rating: 4.6,
    rateno: 164,
    canceledPrice: 15.5,
    currentPrice: 10.5,
  },
  {
    image: "muscle.png",
    imgalt: "muscle",
    author: "Allan Trotter",
    title: "Muscle",
    commentno: 14,
    rating: 4.6,
    rateno: 164,
    canceledPrice: 15.5,
    currentPrice: 10.5,
  },
  {
    image: "thedevinecomedy.png",
    imgalt: "the divine comedy",
    author: "Dante",
    title: "The Divine Comedy",
    commentno: 14,
    rating: 4.6,
    rateno: 164,
    canceledPrice: 15.5,
    currentPrice: 10.5,
  },
  {
    image: "murakami.png",
    imgalt: "Murakami",
    author: "Murakami",
    title: "After Dark",
    commentno: 14,
    rating: 4.6,
    rateno: 164,
    canceledPrice: 15.5,
    currentPrice: 10.5,
  },
  {
    image: "designofeverydaythings.png",
    imgalt: "The Design of Everyday Things",
    author: "Donald Norman",
    title: "The Design of Everyday Things",
    commentno: 14,
    rating: 4.6,
    rateno: 164,
    canceledPrice: 15.5,
    currentPrice: 10.5,
  },
];

export default BookList;
